# Generated by Django 5.2.7 on 2025-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload an identification document (image or PDF) for verification', null=True, upload_to='user_ids/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('R', 'Rejected')], default='P', help_text='Status of identity verification', max_length=1),
        ),
    ]
