# Generated by Django 5.2.7 on 2025-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, help_text='Enter your school or company name for verification', max_length=255, null=True),
        ),
    ]
