# Generated by Django 5.2.7 on 2025-11-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('data', models.JSONField(help_text='Temporarily stored registration data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='users_email_email_49b595_idx'), models.Index(fields=['code'], name='users_email_code_2cd700_idx'), models.Index(fields=['is_used'], name='users_email_is_used_ff90d2_idx')],
            },
        ),
    ]
