# Generated by Django 5.2.7 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Temporary token for email verification', max_length=6, null=True),
        ),
    ]
