# Generated by Django 5.2.7 on 2025-10-27 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text="Why you're interested in this position")),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(help_text='Required qualifications and skills')),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('IT', 'Information Technology'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('SLS', 'Sales'), ('HR', 'Human Resources'), ('ENG', 'Engineering')], default='IT', max_length=3)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('INT', 'Internship'), ('CON', 'Contract')], default='FT', max_length=3)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(help_text='Application deadline')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salary range (optional)', max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
