# Generated by Django 5.2.7 on 2025-10-27 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'is_company': False}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(limit_choices_to={'is_company': True}, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['-date_posted'], name='jobs_jobpos_date_po_d8d5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['category'], name='jobs_jobpos_categor_a7d341_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type'], name='jobs_jobpos_job_typ_34200e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-date_applied'], name='jobs_applic_date_ap_b43c09_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='jobs_applic_status_f83260_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
