# Generated by Django 5.2.7 on 2025-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload any relevant certificates (PDF)', null=True, upload_to='applications/certificates/'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF, DOC, DOCX)', null=True, upload_to='applications/cv/'),
        ),
        migrations.AddField(
            model_name='application',
            name='other_document',
            field=models.FileField(blank=True, help_text='Upload any other supporting document', null=True, upload_to='applications/other/'),
        ),
        migrations.AddField(
            model_name='application',
            name='transcript',
            field=models.FileField(blank=True, help_text='Upload your academic transcript (PDF)', null=True, upload_to='applications/transcripts/'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('GHS', 'GHS - Ghanaian Cedi'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar')], default='USD', help_text='Currency for salary', max_length=3),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this job post is approved by admin'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('IT', 'IT & Software'), ('FIN', 'Finance & Accounting'), ('ACC', 'Accounting'), ('MKT', 'Marketing & Sales'), ('SLS', 'Sales'), ('EDU', 'Education & Training'), ('ENG', 'Engineering'), ('ARC', 'Architecture'), ('HLT', 'Healthcare & Medicine'), ('MED', 'Media & Design'), ('HR', 'Human Resources'), ('LAW', 'Law & Administration'), ('CON', 'Construction & Real Estate'), ('CS', 'Customer Service'), ('OTH', 'Others')], default='IT', max_length=3),
        ),
    ]
