# Generated by Django 5.2.7 on 2025-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_certificate_application_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this job post is approved by admin'),
        ),
    ]
