# Generated by Django 5.2.7 on 2025-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpost_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the job posting', null=True, upload_to='job_images/'),
        ),
    ]
