# Generated by Django 5.2.7 on 2025-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_unread',
            field=models.BooleanField(default=False, help_text='Whether the applicant has an unread notification for status updates'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_unread',
            field=models.BooleanField(default=True, help_text='Whether the company has an unread notification for this application'),
        ),
    ]
