# Generated by Django 5.2.7 on 2025-11-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_applicant_unread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for live location (optional, requires user permission)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for live location (optional, requires user permission)', max_digits=9, null=True),
        ),
    ]
