# Generated by Django 5.2.7 on 2025-11-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpost_latitude_jobpost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateTimeField(help_text='Application deadline (date and time)'),
        ),
    ]
