# Generated by Django 5.2.7 on 2025-11-04 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_application_applicant_unread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('AS', 'Application Submitted'), ('AC', 'Application Status Changed'), ('JP', 'Job Posted'), ('JA', 'Job Approved'), ('JR', 'Job Rejected'), ('IV', 'ID Verified'), ('IR', 'ID Rejected'), ('EV', 'Email Verified')], help_text='Type of notification', max_length=2)),
                ('title', models.CharField(help_text='Short title for the notification', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this notification was created')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, help_text='Related application if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.application')),
                ('related_job', models.ForeignKey(blank=True, help_text='Related job post if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'), models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx')],
            },
        ),
    ]
